name: Tests

on: push

jobs:
    # e2e-tests:
    #     runs-on: ubuntu-20.04
    #     steps:
    #         - name: Check out code ğŸ›
    #           uses: actions/checkout@v2
    #         - name: Run E2E tests ğŸ§ª
    #           uses: cypress-io/github-action@v2
    #           with:
    #               install: true
    #               start: npm start
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install modules
              run: npm install
            - name: Run unit tests ğŸ§ª
              run: npm run test -- --watchAll=false --silent
            # - name: Test coverage
            #   run: npm run test:coverage -- --watchAll=false

    coverage:
        - name: Jest coverage report
          uses: ArtiomTr/jest-coverage-report-action@v2.0.6
          with:
              test-script: npm run test:coverage -- --watchAll=false --silent
